#Mongodb related details
spring.data.mongodb.uri=mongodb://wms:WmsRW@192.168.68.10:27017/?authSource=admin&readPreference=primary&appname=Partner%20Microservice&ssl=false
spring.data.mongodb.host=192.168.68.10
spring.data.mongodb.port=27017
spring.data.mongodb.database=wms
spring.data.mongodb.username=wms
spring.data.mongodb.password=WmsRW
